In [15]:
#一级筛选
#1.天气
from math import*
sum = -(9/14) * log(9/14,2) - (5/14) * log(5/14,2)
a =  5/14*(-(2/5) * log(2/5,2) - (3/5) * log(3/5,2))#晴
b =  4/14*(-1 * log(1,2))#阴
c =  5/14*(-(3/5) * log(3/5,2) - (2/5) * log(2/5,2))#雨
sum1 = a + b + c
print ('Information entropy difference with weather as classification node')
print(sum - sum1)

#结果
#0.2467498197744391

#2.温度
sum = -(9/14) * log(9/14,2) - (5/14) * log(5/14,2)
a =  4/14*(-(1/2) * log(1/2,2) - (1/2) * log(1/2,2))#热
b =  6/14*(-(2/3) * log(2/3,2) - (2/3) * log(2/3,2))#温
c =  4/14*(-(3/4) * log(3/4,2) - (1/4) * log(1/4,2))#凉爽
sum1 = a + b + c
print ('Information entropy difference with temperature as classification node')
print(sum - sum1)
#结果
#0.08851363698450365

#3.湿度
sum = -(9/14) * log(9/14,2) - (5/14) * log(5/14,2)
a =  7/14*(-(3/7) * log(3/7,2) - (4/7) * log(4/7,2))#高
b =  7/14*(-(6/7) * log(6/7,2) - (1/7) * log(1/7,2))#中

sum1 = a + b 
print ('Information entropy difference with humidity as classification node')
print(sum - sum1)
#结果
#0.15183550136234136

#4.是否有风
sum = -(9/14) * log(9/14,2) - (5/14) * log(5/14,2)
a =  6/14*(-(3/6) * log(3/6,2) - (3/6) * log(3/6,2))#是
b =  8/14*(-(6/8) * log(6/8,2) - (2/8) * log(2/8,2))#否

sum1 = a + b 
print ('Information entropy difference with wind as classification node')
print(sum - sum1)
#结果
#0.04812703040826927

#所以一级筛选选择天气

Information entropy difference with weather as classification node
0.2467498197744391
Information entropy difference with temperature as classification node
0.08851363698450365
Information entropy difference with humidity as classification node
0.15183550136234136
Information entropy difference with wind as classification node
0.04812703040826927


In [16]:
#2.1晴
#2.1.1温度
from math import*
sum = -(2/5) * log(2/5,2) - (3/5) * log(3/5,2)
a =  2/5*(-(1/2) * log(1/2,2) - (1/2) * log(1/2,2))#温
#热和凉爽都为0
sum1 = a
print(sum - sum1)
#结果
#0.5709505944546686

#2.1.2湿度
#由于中和高都为0，所以信息增益最大

#2.1.3是否有风
sum = -(2/5) * log(2/5,2) - (3/5) * log(3/5,2)
a =  2/5*(-(1/2) * log(1/2,2) - (1/2) * log(1/2,2))#是
b =  3/5*(-(1/3) * log(1/3,2) - (2/3) * log(2/3,2))#否
sum1 = a + b
print(sum - sum1)
#结果
#0.01997309402197489

#所以在二级筛选中晴天时选择湿度

#2.2阴————全部适合

#2.3雨
#2.3.1温度
sum = -(2/5) * log(2/5,2) - (3/5) * log(3/5,2)
a =  2/5*(-(1/2) * log(1/2,2) - (1/2) * log(1/2,2))#凉爽
b =  3/5*(-(1/3) * log(1/3,2) - (2/3) * log(2/3,2))#温
#热为0
sum1 = a + b
print(sum - sum1)
#结果
#0.01997309402197489

#2.3.2湿度
sum = -(2/5) * log(2/5,2) - (3/5) * log(3/5,2)
a =  2/5*(-(1/2) * log(1/2,2) - (1/2) * log(1/2,2))#高
b =  3/5*(-(1/3) * log(1/3,2) - (2/3) * log(2/3,2))#中
sum1 = a + b
print(sum - sum1)
#结果
#0.01997309402197489

#2.3.3是否有风
#由于有风和无风都为0，所以信息增益最大

#所以在二级筛选中晴天时选择是否有风

0.5709505944546686
0.01997309402197489
0.01997309402197489
0.01997309402197489


In [17]:
import numpy as np
import operator as op
from enum import Enum
class outlook(Enum):
    Sunny = 1
    Overcast = 2
    Rain = 3

class temperature(Enum):
    Hot = 4
    Mild = 5
    Cool = 6
    
class humidity(Enum):
    Normal=7
    High=8
count = {}

x = np.array([temperature.Hot.value,
              humidity.High.value,
              temperature.Hot.value,
              humidity.High.value,
              temperature.Hot.value,
              humidity.High.value,
              temperature.Mild.value,
              humidity.High.value,
              temperature.Cool.value,
              humidity.Normal.value,
              temperature.Cool.value,
              humidity.Normal.value,
              temperature.Cool.value,
              humidity.Normal.value,
              temperature.Mild.value,
              humidity.High.value,
              temperature.Cool.value,
              humidity.Normal.value,
              temperature.Mild.value,
              humidity.Normal.value,
              temperature.Mild.value,
              humidity.Normal.value,
              temperature.Mild.value,
              humidity.High.value,
              temperature.Hot.value,
              humidity.Normal.value,
              temperature.Mild.value,
              humidity.High.value
             ])
for i in x[0:len(x)-1]:
    count[i] = count.get(i, 0) + 1
count = sorted(count.items(), key=op.itemgetter(0), reverse=False)
 
markov_marix = np.zeros([len(count), len(count)])
for j in range(len(x)-1):
    for m in range(len(count)):
        for n in range(len(count)):
            if x[j] == count[m][0] and x[j+1] == count[n][0]:
                markov_marix[m][n] += 1
for t in range(len(count)):
    markov_marix[t, :] /= count[t][1]
print(markov_marix)

[[0.         0.         0.         0.25       0.75      ]
 [0.         0.         0.         0.33333333 0.66666667]
 [0.         0.         0.         1.         0.        ]
 [0.         0.71428571 0.28571429 0.         0.        ]
 [0.5        0.16666667 0.33333333 0.         0.        ]]


In [18]:
import numpy as np
import operator as op
from enum import Enum

class temperature(Enum):
    Hot = 4
    Mild = 5
    Cool = 6
    
class humidity(Enum):
    Normal=7
    High=8
    
x = np.array([temperature.Hot.value,
              humidity.High.value,
              temperature.Hot.value,
              humidity.High.value,
              temperature.Hot.value,
              humidity.High.value,
              temperature.Mild.value,
              humidity.High.value,
              temperature.Cool.value,
              humidity.Normal.value,
              temperature.Cool.value,
              humidity.Normal.value,
              temperature.Cool.value,
              humidity.Normal.value,
              temperature.Mild.value,
              humidity.High.value,
              temperature.Cool.value,
              humidity.Normal.value,
              temperature.Mild.value,
              humidity.Normal.value,
              temperature.Mild.value,
              humidity.Normal.value,
              temperature.Mild.value,
              humidity.High.value,
              temperature.Hot.value,
              humidity.Normal.value,
              temperature.Mild.value,
              humidity.High.value
             ])    

count = {}
for i in x[0:len(x)-1]:
    count[i] = count.get(i, 0) + 1
count = sorted(count.items(), key=op.itemgetter(0), reverse=False)
 
markov_marix = np.zeros([len(count), len(count)])
for j in range(len(x)-1):
    for m in range(len(count)):
        for n in range(len(count)):
            if x[j] == count[m][0] and x[j+1] == count[n][0]:
                markov_marix[m][n] += 1
for t in range(len(count)):
    markov_marix[t, :] /= count[t][1]
print(markov_marix)

[[0.         0.         0.         0.25       0.75      ]
 [0.         0.         0.         0.33333333 0.66666667]
 [0.         0.         0.         1.         0.        ]
 [0.         0.71428571 0.28571429 0.         0.        ]
 [0.5        0.16666667 0.33333333 0.         0.        ]]


In [19]:
import numpy as np
import operator as op
from enum import Enum
    
class humidity(Enum):
    Normal=7
    High=8
    
class wind(Enum):
    Weak=9
    Strong=10 
    
x = np.array([humidity.High.value,
              wind.Weak.value,
              humidity.High.value,
              wind.Strong.value,
              humidity.High.value,
              wind.Weak.value,
              humidity.High.value,
              wind.Weak.value,
              humidity.Normal.value,
              wind.Weak.value,
              humidity.Normal.value,
              wind.Strong.value,
              humidity.Normal.value,
              wind.Strong.value,
              humidity.High.value,
              wind.Weak.value,
              humidity.Normal.value,
              wind.Weak.value,
              humidity.Normal.value,
              wind.Weak.value,
              humidity.Normal.value,
              wind.Strong.value,
              humidity.High.value,
              wind.Strong.value,
              humidity.Normal.value,
              wind.Weak.value,
              humidity.High.value,
              wind.Strong.value
             ])    

count = {}
for i in x[0:len(x)-1]:
    count[i] = count.get(i, 0) + 1
count = sorted(count.items(), key=op.itemgetter(0), reverse=False)
 
markov_marix = np.zeros([len(count), len(count)])
for j in range(len(x)-1):
    for m in range(len(count)):
        for n in range(len(count)):
            if x[j] == count[m][0] and x[j+1] == count[n][0]:
                markov_marix[m][n] += 1
for t in range(len(count)):
    markov_marix[t, :] /= count[t][1]
print(markov_marix)

[[0.         0.         0.57142857 0.42857143]
 [0.         0.         0.57142857 0.42857143]
 [0.625      0.375      0.         0.        ]
 [0.4        0.6        0.         0.        ]]


In [20]:
import numpy as np
import operator as op
from enum import Enum
    
class wind(Enum):
    Weak=9
    Strong=10 
    
class state(Enum):
    yes=11
    no=12
x = np.array([wind.Weak.value,
              state.no.value,
              wind.Strong.value,
              state.no.value,
              wind.Weak.value,
              state.yes.value,
              wind.Weak.value,
              state.yes.value,
              wind.Weak.value,
              state.yes.value,
              wind.Strong.value,
              state.no.value,
              wind.Strong.value,
              state.yes.value,
              wind.Weak.value,
              state.no.value,
              wind.Weak.value,
              state.yes.value,
              wind.Weak.value,
              state.yes.value,
              wind.Strong.value,
              state.yes.value,
              wind.Strong.value,
              state.yes.value,
              wind.Weak.value,
              state.yes.value,
              wind.Strong.value,
              state.yes.value
             ])    

count = {}
for i in x[0:len(x)-1]:
    count[i] = count.get(i, 0) + 1
count = sorted(count.items(), key=op.itemgetter(0), reverse=False)
 
markov_marix = np.zeros([len(count), len(count)])
for j in range(len(x)-1):
    for m in range(len(count)):
        for n in range(len(count)):
            if x[j] == count[m][0] and x[j+1] == count[n][0]:
                markov_marix[m][n] += 1
for t in range(len(count)):
    markov_marix[t, :] /= count[t][1]
print(markov_marix)

[[0.         0.         0.75       0.25      ]
 [0.         0.         0.66666667 0.33333333]
 [0.55555556 0.44444444 0.         0.        ]
 [0.5        0.5        0.         0.        ]]


In [21]:
from sklearn.externals.six import StringIO 
from sklearn import tree 
import pydot 
import pydotplus
# Four columns from the table above with values 
# 1st col －工for Sunny, 2 for Overcast, and 3 for Rainy 
# 2nd col - 1 for Hot, 2 for Mild, 3 for Cool 
# 3rd col - 1 for High and 2 for Normal 
# 4th col - 0 for Weak and 1 for Strong 
X=[[1,1,1,0],[1,1,1,1],[2,1,1,0],[2,3,2,1],[1,2,1,0],[1,3,2,0],[3,2,1,0],[3,3,2,0],[3,3,2,1],[3,2,2,0],[1,2,2,1],[2,2,1,1],[2,1,2,0],[3,2,1,0]]
# 1 for Play and O for Don ’t Play 
Y=[0,0,1,1,0,1,1,1,0,1,1,1,1,0]

clf = tree.DecisionTreeClassifier() 
clf = clf. fit (X, Y) 
dot_data = StringIO() 
tree.export_graphviz(clf, out_file=dot_data) 
graph = pydot.graph_from_dot_data(dot_data.getvalue()) 
graph[0].write_pdf("game.pdf") 